---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base/]
namespace: default
labels:
  - includeSelectors: true
    pairs:
      app: stock-backtest-writer-test
images:
  - name: stock-backtest-writer-test
    newName: stock-backtest-writer-test
    newTag: latest
